=== project-chip/connectedhomeip/src/app/zap-templates/zcl/zcl.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:annotation>
    <xs:documentation>
This schema describes the format of the XML files, that describe the ZCL specification.

(c) Copyright 2012, 2021, Silicon Laboratories Inc.
  </xs:documentation>
  </xs:annotation>
  <xs:complexType name="access">
    <xs:attribute name="op" type="xs:string"/>
    <xs:attribute name="role" type="xs:string"/>
    <xs:attribute name="privilege" type="xs:string"/>
    <xs:attribute name="modifier" type="xs:string"/>
  </xs:complexType>
  <xs:complexType name="eventField">
    <xs:attribute name="id" use="required" type="xs:string"/>
    <xs:attribute name="name" use="required" type="xs:string"/>
    <xs:attribute name="type" use="required" type="xs:string"/>
    <xs:attribute name="array" use="optional" type="xs:boolean"/>
    <xs:attribute name="isNullable" use="optional" type="xs:boolean"/>
  </xs:complexType>
  <xs:complexType name="tag">
    <xs:attribute name="name" use="required" type="xs:string"/>
    <xs:attribute name="description" use="required" type="xs:string"/>
  </xs:complexType>
  <xs:complexType name="arg">
    <xs:attribute name="arrayLength" type="xs:boolean"/>
    <xs:attribute name="array" type="xs:boolean"/>
    <xs:attribute name="default" type="xs:string"/>
    <xs:attribute name="description" type="xs:string"/>
    <xs:attribute name="introducedIn" type="zclSpecVersion"/>
    <xs:attribute name="removedIn" type="zclSpecVersion"/>
    <xs:attribute name="name" use="required"/>
    <xs:attribute name="type" use="required"/>
    <xs:attribute name="length" type="xs:int"/>
    <xs:attribute name="presentIf" type="xs:string"/>
    <xs:attribute name="optional" type="xs:integer"/>
    <xs:attribute name="fieldId" type="xs:integer"/>
    <xs:attribute name="countArg" type="xs:string" use="optional"/>
    <xs:attribute name="isNullable" type="xs:boolean"/>
  </xs:complexType>
  <xs:complexType name="clusterRef">
    <xs:attribute name="code" type="xs:string"/>
  </xs:complexType>
  <xs:complexType name="item">
    <xs:attribute name="introducedIn" type="zclSpecVersion"/>
    <xs:attribute name="name" use="required" type="xs:string"/>
    <xs:attribute name="type" type="xs:string"/>
    <xs:attribute name="value" type="xs:string"/>
    <xs:attribute name="array" type="xs:boolean"/>
    <xs:attribute name="enum" type="xs:boolean"/>
    <xs:attribute name="fieldId" type="xs:integer"/>
    <xs:attribute name="isNullable" type="xs:boolean"/>
  </xs:complexType>
  <xs:complexType name="featureBit" mixed="true">
    <xs:attribute name="tag" use="required" type="xs:string"/>
    <xs:attribute name="bit" use="required" type="xs:integer"/>
  </xs:complexType>
  <xs:element name="cli">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="group"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="command"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="defaultAccess">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="access" type="access"/>
      </xs:sequence>
      <xs:attribute name="type" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="operation">
    <xs:complexType>
      <xs:attribute name="type" type="xs:string"/>
      <xs:attribute name="description" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="modifier">
    <xs:complexType>
      <xs:attribute name="type" type="xs:string"/>
      <xs:attribute name="description" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="role">
    <xs:complexType>
      <xs:attribute name="type" type="xs:string"/>
      <xs:attribute name="description" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="privilege" substitutionGroup="role"/>
  <xs:element name="accessControl">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="operation"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="modifier"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="role"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="group">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="description"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="name" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="zap" substitutionGroup="configurator"/>
  <xs:element name="configurator">
    <xs:complexType>
      <xs:sequence>
        <xs:choice>
          <xs:element ref="callback"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="deviceType"/>
        </xs:choice>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element ref="atomic"/>
          <xs:element ref="bitmap"/>
          <xs:element ref="cluster"/>
          <xs:element ref="clusterExtension"/>
          <xs:element ref="enum"/>
          <xs:element ref="struct"/>
          <xs:element ref="domain"/>
          <xs:element ref="global"/>
          <xs:element ref="tag"/>
          <xs:element ref="accessControl"/>
          <xs:element ref="defaultAccess"/>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="deviceType">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="domain"/>
        <xs:element ref="typeName"/>
        <xs:element ref="profileId"/>
        <xs:element ref="deviceId"/>
        <xs:element minOccurs="0" ref="channels"/>
        <xs:element ref="clusters"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="typeName" type="xs:string"/>
  <xs:element name="profileId">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="editable" use="required" type="xs:boolean"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="deviceId">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="editable" use="required" type="xs:boolean"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="channels">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="channel"/>
      </xs:sequence>
      <xs:attribute name="editable" use="required" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="channel">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:minInclusive value="11"/>
        <xs:maxInclusive value="26"/>
        <xs:whiteSpace value="collapse"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="clusters">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="include"/>
      </xs:sequence>
      <xs:attribute name="lockOthers" use="required" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="include">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="requireAttribute"/>
        <xs:element ref="requireCommand"/>
      </xs:choice>
      <xs:attribute name="client" use="required" type="xs:boolean"/>
      <xs:attribute name="clientLocked" use="required" type="xs:boolean"/>
      <xs:attribute name="cluster"/>
      <xs:attribute name="server" use="required" type="xs:boolean"/>
      <xs:attribute name="serverLocked" use="required" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="requireAttribute" type="zclAttributeDefine"/>
  <xs:element name="requireCommand" type="zclCommandName"/>
  <xs:element name="global">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="command"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="attribute"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="atomic">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="type"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="type">
    <xs:complexType>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="description" use="required" type="xs:string"/>
      <xs:attribute name="size" type="xs:integer"/>
      <xs:attribute name="discrete" type="xs:boolean"/>
      <xs:attribute name="signed" type="xs:boolean"/>
      <xs:attribute name="string" type="xs:boolean"/>
      <xs:attribute name="char" type="xs:boolean"/>
      <xs:attribute name="long" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="bitmap">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="cluster"/>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="field"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="type" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="field">
    <xs:complexType>
      <xs:attribute name="mask" use="required" type="xs:string"/>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="introducedIn" type="zclSpecVersion"/>
      <xs:attribute name="fieldId" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="globalAttribute">
    <xs:complexType mixed="true">
      <xs:choice>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="featureBit" type="featureBit"/>
      </xs:choice>
      <xs:attribute name="side" use="required" type="zclSideWithEither"/>
      <xs:attribute name="code" use="required" type="xs:string"/>
      <xs:attribute name="value" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="cluster">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="domain"/>
        <xs:element ref="description"/>
        <xs:element ref="code"/>
        <xs:element ref="define"/>
        <xs:element ref="client"/>
        <xs:element ref="server"/>
        <xs:element minOccurs="0" ref="generateCmdHandlers"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="tag" type="tag"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="globalAttribute"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="attribute"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="command"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="event"/>
      </xs:sequence>
      <xs:attribute name="introducedIn" type="xs:string"/>
      <xs:attribute name="manufacturerCode" type="zclCode"/>
      <xs:attribute name="singleton" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="code" type="zclCode"/>
  <xs:element name="define" type="xs:string"/>
  <xs:element name="client">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:boolean">
          <xs:attribute name="init" use="required" type="xs:boolean"/>
          <xs:attribute name="tick" use="required" type="xs:boolean"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="server">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:boolean">
          <xs:attribute name="init" use="required" type="xs:boolean"/>
          <xs:attribute name="tick" use="required" type="xs:boolean"/>
          <xs:attribute name="tickFrequency" type="xs:string"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="generateCmdHandlers" type="xs:boolean"/>
  <xs:element name="clusterExtension">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="attribute"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="command"/>
      </xs:sequence>
      <xs:attribute name="code" use="required" type="xs:string"/>
      <xs:attribute name="introducedIn" type="zclSpecVersion"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="enum">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="cluster" type="clusterRef"/>
        <xs:element maxOccurs="unbounded" name="item" type="item"/>
      </xs:sequence>
      <xs:attribute name="description"/>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="type" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="struct">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="cluster" type="clusterRef"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="item" type="item"/>
      </xs:sequence>
      <xs:attribute name="length" type="xs:integer"/>
      <xs:attribute name="name" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="callback">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="function"/>
      </xs:sequence>
      <xs:attribute name="postfix" type="xs:string"/>
      <xs:attribute name="prefix" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="function">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="description"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="arg" type="arg"/>
        <xs:element minOccurs="0" ref="codeForStub"/>
      </xs:sequence>
      <xs:attribute name="category" type="xs:string"/>
      <xs:attribute name="cluster"/>
      <xs:attribute name="consumed" type="xs:boolean"/>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="name" use="required"/>
      <xs:attribute name="platformType" type="xs:string"/>
      <xs:attribute name="returnType" use="required" type="xs:string"/>
      <xs:attribute name="side" type="zclSide"/>
      <xs:attribute name="stackMacro"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="codeForStub" type="xs:string"/>
  <xs:element name="name" type="xs:string"/>
  <xs:element name="tag" type="tag"/>
  <xs:element name="domain">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="older"/>
      </xs:sequence>
      <xs:attribute name="dependsOn" type="zclSpecVersion"/>
      <xs:attribute name="name"/>
      <xs:attribute name="spec" type="zclSpecVersion"/>
      <xs:attribute name="certifiable" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="older">
    <xs:complexType>
      <xs:attribute name="dependsOn" use="optional" type="xs:string"/>
      <xs:attribute name="spec" use="required" type="xs:string"/>
      <xs:attribute name="certifiable" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="event">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="description"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="access" type="access"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="field" type="eventField"/>
      </xs:sequence>
      <xs:attribute name="code" type="xs:string"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="side" use="required" type="zclSide"/>
      <xs:attribute name="priority" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="command">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="description"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="access" type="access"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="arg" type="arg"/>
      </xs:sequence>
      <xs:attribute name="cli"/>
      <xs:attribute name="cliFunctionName" type="xs:string"/>
      <xs:attribute name="code" type="xs:string"/>
      <xs:attribute name="disableDefaultResponse" type="xs:boolean"/>
      <xs:attribute name="functionName" type="xs:string"/>
      <xs:attribute name="group" type="xs:string"/>
      <xs:attribute name="introducedIn" type="zclSpecVersion"/>
      <xs:attribute name="noDefaultImplementation" type="xs:boolean"/>
      <xs:attribute name="manufacturerCode" type="xs:string"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="optional" type="xs:boolean"/>
      <xs:attribute name="source" type="xs:string"/>
      <xs:attribute name="restriction" type="xs:string"/>
      <xs:attribute name="response" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="attribute">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="description"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="access" type="access"/>
      </xs:sequence>
      <xs:attribute name="code" use="required" type="zclCode"/>
      <xs:attribute name="default"/>
      <xs:attribute name="define" use="required" type="zclAttributeDefine"/>
      <xs:attribute name="introducedIn" type="zclSpecVersion"/>
      <xs:attribute name="length" type="xs:integer"/>
      <xs:attribute name="manufacturerCode" type="zclCode"/>
      <xs:attribute name="max" type="xs:anySimpleType"/>
      <xs:attribute name="min" type="xs:anySimpleType"/>
      <xs:attribute name="reportMaxInterval" type="xs:anySimpleType"/>
      <xs:attribute name="reportMinInterval" type="xs:anySimpleType"/>
      <xs:attribute name="reportableChange" type="xs:anySimpleType"/>
      <xs:attribute name="optional" use="required" type="xs:boolean"/>
      <xs:attribute name="side" use="required" type="zclSide"/>
      <xs:attribute name="type" use="required" type="xs:string"/>
      <xs:attribute name="readable" type="xs:boolean"/>
      <xs:attribute name="writable" type="xs:boolean"/>
      <xs:attribute name="reportable" type="xs:boolean"/>
      <xs:attribute name="array" type="xs:boolean"/>
      <xs:attribute name="isNullable" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="description">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="arg" type="arg"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="zclAttributeDefine">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>
  <xs:simpleType name="zclCommandName">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>
  <xs:simpleType name="zclSpecVersion">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>
  <xs:simpleType name="zclCode">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>
  <xs:simpleType name="zclSide">
    <xs:restriction base="xs:string">
      <xs:enumeration value="client"/>
      <xs:enumeration value="server"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="zclSideWithEither">
    <xs:restriction base="xs:string">
      <xs:enumeration value="client"/>
      <xs:enumeration value="server"/>
      <xs:enumeration value="either"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="mapping">
    <xs:complexType>
      <xs:attribute name="code" type="xs:string"/>
      <xs:attribute name="translation" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="map">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="mapping"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== project-chip/connectedhomeip/src/app/zap-templates/zcl/data-model/chip/tls-certificate-management-cluster.xml
<?xml version="1.0"?>
<!--
Copyright (c) 2024-2026 Project CHIP Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
<!--
XML generated by Alchemy; DO NOT EDIT.
Source: src/tls/TLSCertificateManagement.adoc
Parameters: zap attribute=in-progress sdkRoot=./ specRoot=../../ConnectedHomeIP-Spec/connectedhomeip-spec/ ../../ConnectedHomeIP-Spec/connectedhomeip-spec/src/app_clusters/PushAVStreamTransport.adoc 
Git: 0.9.1-summer2026-834-gad55520e7
Alchemy: v1.6.16
-->
<configurator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../zcl.xsd">
  <domain name="General"/>
  <struct name="TLSCertStruct" apiMaturity="provisional" isFabricScoped="true">
    <cluster code="0x0801"/>
    <item fieldId="0" name="CAID" type="int16u" min="0" max="65534"/>
    <item fieldId="1" name="Certificate" type="long_octet_string" length="3000" optional="true"/>
  </struct>

  <struct name="TLSClientCertificateDetailStruct" apiMaturity="provisional" isFabricScoped="true">
    <cluster code="0x0801"/>
    <item fieldId="0" name="CCDID" type="int16u" min="0" max="65534"/>
    <item fieldId="1" name="ClientCertificate" type="long_octet_string" length="3000" optional="true" isNullable="true"/>
    <item fieldId="2" name="IntermediateCertificates" array="true" type="octet_string" optional="true" length="10"/>
  </struct>

  <cluster>
    <domain name="General">General</domain>
    <name>TLS Certificate Management</name>
    <code>0x0801</code>
    <define>TLS_CERTIFICATE_MANAGEMENT_CLUSTER</define>
    <description>This Cluster is used to manage TLS Client Certificates and to provision
      TLS endpoints with enough information to facilitate subsequent connection.</description>
    <client init="false" tick="false">true</client>
    <server init="false" tick="false">true</server>
    <globalAttribute code="0xFFFD" side="either" value="1"/>
    <attribute code="0x0000" side="server" name="MaxRootCertificates" define="MAX_ROOT_CERTIFICATES" type="int8u" min="5" max="254"/>
    <attribute code="0x0001" side="server" name="ProvisionedRootCertificates" define="PROVISIONED_ROOT_CERTIFICATES" type="array" entryType="TLSCertStruct" length="254" isFabricSensitive="true"/>
    <attribute code="0x0002" side="server" name="MaxClientCertificates" define="MAX_CLIENT_CERTIFICATES" type="int8u" min="2" max="254"/>
    <attribute code="0x0003" side="server" name="ProvisionedClientCertificates" define="PROVISIONED_CLIENT_CERTIFICATES" type="array" entryType="TLSClientCertificateDetailStruct" length="254" isFabricSensitive="true"/>
    <command code="0x00" source="client" name="ProvisionRootCertificate" response="ProvisionRootCertificateResponse" isFabricScoped="true">
      <description>This command SHALL provision a newly provided certificate, or rotate an existing one, based on the contents of the CAID field.</description>
      <access op="invoke" privilege="administer"/>
      <quality largeMessage="true"/>
      <arg fieldId="0" name="Certificate" type="long_octet_string" length="3000"/>
      <arg fieldId="1" name="CAID" type="int16u" isNullable="true"/>
    </command>

    <command code="0x01" source="server" name="ProvisionRootCertificateResponse" disableDefaultResponse="true">
      <description>This command SHALL be generated in response to a ProvisionRootCertificate command.</description>
      <quality largeMessage="true"/>
      <arg fieldId="0" name="CAID" type="int16u" min="0" max="65534"/>
    </command>

    <command code="0x02" source="client" name="FindRootCertificate" response="FindRootCertificateResponse" isFabricScoped="true">
      <description>This command SHALL return the specified TLS root certificate, or all provisioned TLS root certificates for the accessing fabric, based on the contents of the CAID field.</description>
      <quality largeMessage="true"/>
      <arg fieldId="0" name="CAID" type="int16u" isNullable="true"/>
    </command>

    <command code="0x03" source="server" name="FindRootCertificateResponse" disableDefaultResponse="true">
      <description>This command SHALL be generated in response to a FindRootCertificate command.</description>
      <quality largeMessage="true"/>
      <arg fieldId="0" name="CertificateDetails" array="true" type="TLSCertStruct" minLength="1" length="254"/>
    </command>

    <command code="0x04" source="client" name="LookupRootCertificate" response="LookupRootCertificateResponse" isFabricScoped="true">
      <description>This command SHALL return the CAID for the passed in fingerprint.</description>
      <quality largeMessage="true"/>
      <arg fieldId="0" name="Fingerprint" type="octet_string" length="64"/>
    </command>

    <command code="0x05" source="server" name="LookupRootCertificateResponse" disableDefaultResponse="true">
      <description>This command SHALL be generated in response to a LookupRootCertificate command.</description>
      <quality largeMessage="true"/>
      <arg fieldId="0" name="CAID" type="int16u" min="0" max="65534"/>
    </command>

    <command code="0x06" source="client" name="RemoveRootCertificate" isFabricScoped="true">
      <description>This command SHALL be generated to request the server removes the certificate provisioned to the provided Certificate Authority ID.</description>
      <access op="invoke" privilege="administer"/>
      <quality largeMessage="true"/>
      <arg fieldId="0" name="CAID" type="int16u" min="0" max="65534"/>
    </command>

    <command code="0x07" source="client" name="ClientCSR" response="ClientCSRResponse" isFabricScoped="true">
      <description>This command SHALL be generated to request the Node generates a certificate signing request for a new TLS key pair or use an existing CCDID for certificate rotation.</description>
      <access op="invoke" privilege="administer"/>
      <quality largeMessage="true"/>
      <arg fieldId="0" name="Nonce" type="octet_string" length="32" minLength="32"/>
      <arg fieldId="1" name="CCDID" type="int16u" min="0" max="65534" isNullable="true"/>
    </command>

    <command code="0x08" source="server" name="ClientCSRResponse" disableDefaultResponse="true">
      <description>This command SHALL be generated in response to a ClientCSR command.</description>
      <quality largeMessage="true"/>
      <arg fieldId="0" name="CCDID" type="int16u" min="0" max="65534"/>
      <arg fieldId="1" name="CSR" type="long_octet_string" length="3000"/>
      <arg fieldId="2" name="NonceSignature" type="octet_string" length="128"/>
    </command>

    <command code="0x09" source="client" name="ProvisionClientCertificate" isFabricScoped="true">
      <description>This command SHALL be generated to request the Node provisions newly provided Client Certificate Details, or rotate an existing client certificate.</description>
      <access op="invoke" privilege="administer"/>
      <quality largeMessage="true"/>
      <arg fieldId="0" name="CCDID" type="int16u" min="0" max="65534"/>
      <arg fieldId="1" name="ClientCertificate" type="long_octet_string" length="3000"/>
      <arg fieldId="2" name="IntermediateCertificates" array="true" type="octet_string" length="10"/>
    </command>

    <command code="0x0A" source="client" name="FindClientCertificate" isFabricScoped="true" response="FindClientCertificateResponse">
      <description>This command SHALL return the TLSClientCertificateDetailStruct for the passed in CCDID, or all TLS client certificates for the accessing fabric, based on the contents of the CCDID field.</description>
      <quality largeMessage="true"/>
      <arg fieldId="0" name="CCDID" type="int16u" isNullable="true"/>
    </command>

    <command code="0x0B" source="server" name="FindClientCertificateResponse" disableDefaultResponse="true">
      <description>This command SHALL be generated in response to a FindClientCertificate command.</description>
      <quality largeMessage="true"/>
      <arg fieldId="0" name="CertificateDetails" array="true" type="TLSClientCertificateDetailStruct" minLength="1" length="254"/>
    </command>

    <command code="0x0C" source="client" name="LookupClientCertificate" isFabricScoped="true" response="LookupClientCertificateResponse">
      <description>This command SHALL return the CCDID for the passed in Fingerprint.</description>
      <quality largeMessage="true"/>
      <arg fieldId="0" name="Fingerprint" type="octet_string" length="64"/>
    </command>

    <command code="0x0D" source="server" name="LookupClientCertificateResponse" disableDefaultResponse="true">
      <description>This command SHALL be generated in response to a LookupClientCertificate command.</description>
      <quality largeMessage="true"/>
      <arg fieldId="0" name="CCDID" type="int16u" min="0" max="65534"/>
    </command>

    <command code="0x0E" source="client" name="RemoveClientCertificate" isFabricScoped="true">
      <description>This command SHALL be used to request the Node removes all stored information for the provided CCDID.</description>
      <access op="invoke" privilege="administer"/>
      <quality largeMessage="true"/>
      <arg fieldId="0" name="CCDID" type="int16u" min="0" max="65534"/>
    </command>

  </cluster>
</configurator>
