=== project-chip/connectedhomeip/src/app/zap-templates/zcl/data-model/silabs/schema/zcl.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (c) 2008,2020 Silicon Labs.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="qualified">
    <xs:annotation>
      <xs:documentation>This schema describes the format of the XML files, that describe the ZCL specification.
It does not describe over-the-air format of the packet.

Copyright 2012, Silicon Laboratories Inc.</xs:documentation></xs:annotation>
    <xs:element name="cli">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="group" />
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="command" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="group">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="description" />
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:string" />
      <xs:attribute name="name" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="configurator">
    <xs:complexType>
      <xs:sequence>
        <xs:choice>
          <xs:element ref="callback" />
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="deviceType" />
        </xs:choice>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element minOccurs="0" ref="global" />
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="domain" />
        </xs:choice>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element ref="atomic" />
          <xs:element ref="bitmap" />
          <xs:element ref="cluster" />
          <xs:element ref="clusterExtension" />
          <xs:element ref="enum" />
          <xs:element ref="struct" />
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="deviceType">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name" />
        <xs:element ref="domain" />
        <xs:element ref="typeName" />
        <xs:element ref="zigbeeType" />
        <xs:element ref="profileId" />
        <xs:element ref="deviceId" />
        <xs:element minOccurs="0" ref="channels" />
        <xs:element ref="clusters" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="typeName" type="xs:string" />
  <xs:element name="zigbeeType">
    <xs:complexType mixed="true">
      <xs:attribute name="editable" use="optional" type="xs:boolean" />
    </xs:complexType>
  </xs:element>
  <xs:element name="profileId">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="editable" use="required" type="xs:boolean" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="deviceId">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="editable" use="required" type="xs:boolean" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="channels">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="channel" />
      </xs:sequence>
      <xs:attribute name="editable" use="required" type="xs:boolean" />
    </xs:complexType>
  </xs:element>
  <xs:element name="channel">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:minInclusive value="11"></xs:minInclusive>
        <xs:maxInclusive value="26"></xs:maxInclusive>
        <xs:whiteSpace value="collapse"></xs:whiteSpace>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="clusters">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="include" />
      </xs:sequence>
      <xs:attribute name="lockOthers" use="required" type="xs:boolean" />
    </xs:complexType>
  </xs:element>
  <xs:element name="include">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="requireAttribute" />
        <xs:element ref="requireCommand" />
      </xs:choice>
      <xs:attribute name="client" use="required" type="xs:boolean" />
      <xs:attribute name="clientLocked" use="required" type="xs:boolean" />
      <xs:attribute name="cluster" />
      <xs:attribute name="server" use="required" type="xs:boolean" />
      <xs:attribute name="serverLocked" use="required" type="xs:boolean" />
    </xs:complexType>
  </xs:element>
  <xs:element name="requireAttribute" type="zclAttributeDefine" />
  <xs:element name="requireCommand" type="zclCommandName" />
  <xs:element name="global">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="command" />
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="attribute" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="atomic">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="type" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="type">
    <xs:complexType>
      <xs:attribute name="id" use="required" type="xs:string" />
      <xs:attribute name="name" use="required" type="xs:string" />
      <xs:attribute name="description" use="required" type="xs:string" />
      <xs:attribute name="size" type="xs:integer" />
      <xs:attribute name="discrete" type="xs:boolean" />
    </xs:complexType>
  </xs:element>
  <xs:element name="bitmap">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="field" />
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:string" />
      <xs:attribute name="type" use="required" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="field">
    <xs:complexType>
      <xs:attribute name="mask" use="required" type="xs:string" />
      <xs:attribute name="name" use="required" type="xs:string" />
      <xs:attribute name="introducedIn" type="zclSpecVersion" />
    </xs:complexType>
  </xs:element>
  <xs:element name="globalAttribute">
    <xs:complexType>
      <xs:attribute name="side" use="required" type="zclSideWithEither" />
      <xs:attribute name="code" use="required" type="xs:string" />
      <xs:attribute name="value" use="required" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="cluster">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name" />
        <xs:element ref="domain" />
        <xs:element ref="description" />
        <xs:element ref="code" />
        <xs:element ref="define" />
        <xs:element ref="client" />
        <xs:element ref="server" />
        <xs:element minOccurs="0" ref="generateCmdHandlers" />
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="globalAttribute" />
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="attribute" />
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="command" />
      </xs:sequence>
      <xs:attribute name="introducedIn" type="xs:string" />
      <xs:attribute name="manufacturerCode" type="zclCode" />
      <xs:attribute name="singleton" type="xs:boolean" />
    </xs:complexType>
  </xs:element>
  <xs:element name="code" type="zclCode" />
  <xs:element name="define" type="xs:string" />
  <xs:element name="client">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:boolean">
          <xs:attribute name="init" use="required" type="xs:boolean" />
          <xs:attribute name="tick" use="required" type="xs:boolean" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="server">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:boolean">
          <xs:attribute name="init" use="required" type="xs:boolean" />
          <xs:attribute name="tick" use="required" type="xs:boolean" />
          <xs:attribute name="tickFrequency" type="xs:string" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="generateCmdHandlers" type="xs:boolean" />
  <xs:element name="clusterExtension">
    <xs:complexType>
    	<xs:sequence>
    		<xs:element minOccurs="0" maxOccurs="unbounded"
    			ref="attribute" />
    		<xs:element minOccurs="0" maxOccurs="unbounded"
    			ref="command" />
    	</xs:sequence>
    	<xs:attribute name="code" use="required" type="xs:string" />
    	<xs:attribute name="introducedIn" type="zclSpecVersion"></xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="enum">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="item" />
      </xs:sequence>
      <xs:attribute name="description" />
      <xs:attribute name="name" use="required" type="xs:string" />
      <xs:attribute name="type" use="required" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="struct">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="item" />
      </xs:sequence>
      <xs:attribute name="length" type="xs:integer" />
      <xs:attribute name="name" use="required" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="callback">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="function" />
      </xs:sequence>
      <xs:attribute name="postfix" type="xs:string" />
      <xs:attribute name="prefix" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="function">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="description" />
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="arg" />
        <xs:element minOccurs="0" ref="codeForStub" />
      </xs:sequence>
      <xs:attribute name="category" type="xs:string" />
      <xs:attribute name="cluster" />
      <xs:attribute name="consumed" type="xs:boolean" />
      <xs:attribute name="id" use="required" type="xs:string" />
      <xs:attribute name="name" use="required" />
      <xs:attribute name="platformType" type="xs:string" />
      <xs:attribute name="returnType" use="required" type="xs:string" />
      <xs:attribute name="side" type="zclSide" />
      <xs:attribute name="stackMacro" />
    </xs:complexType>
  </xs:element>
  <xs:element name="codeForStub" type="xs:string" />
  <xs:element name="name" type="xs:string" />
  <xs:element name="domain">
    <xs:complexType mixed="true">
    	<xs:sequence>
    		<xs:element minOccurs="0" maxOccurs="unbounded" ref="older" />
    	</xs:sequence>
    	<xs:attribute name="dependsOn" type="zclSpecVersion" />
    	<xs:attribute name="name" />
    	<xs:attribute name="spec" type="zclSpecVersion" />
    	<xs:attribute name="certifiable" type="xs:boolean"></xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="older">
    <xs:complexType>
    	<xs:attribute name="dependsOn" use="optional" type="xs:string" />
    	<xs:attribute name="spec" use="required" type="xs:string" />
    	<xs:attribute name="certifiable" type="xs:boolean"></xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="command">
    <xs:complexType>
    	<xs:sequence>
    		<xs:element ref="description" />
    		<xs:element minOccurs="0" maxOccurs="unbounded" ref="arg" />
    	</xs:sequence>
    	<xs:attribute name="cli" />
    	<xs:attribute name="cliFunctionName" type="xs:string" />
    	<xs:attribute name="code" type="xs:string" />
    	<xs:attribute name="disableDefaultResponse" type="xs:boolean" />
    	<xs:attribute name="functionName" type="xs:string" />
    	<xs:attribute name="group" type="xs:string" />
    	<xs:attribute name="introducedIn" type="zclSpecVersion" />
    	<xs:attribute name="noDefaultImplementation" type="xs:boolean"></xs:attribute>
    	<xs:attribute name="manufacturerCode" type="xs:string" />
    	<xs:attribute name="name" type="xs:string" />
    	<xs:attribute name="optional" type="xs:boolean" />
    	<xs:attribute name="source" type="xs:string" />
    	<xs:attribute name="restriction" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="item">
    <xs:complexType>
    	<xs:attribute name="introducedIn" type="zclSpecVersion" />
    	<xs:attribute name="name" use="required" type="xs:string" />
    	<xs:attribute name="type" type="xs:string" />
    	<xs:attribute name="value" type="xs:string" />
    	<xs:attribute name="array" type="xs:boolean"></xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="attribute">
    <xs:complexType mixed="true">
    	<xs:attribute name="code" use="required" type="zclCode" />
    	<xs:attribute name="default" />
    	<xs:attribute name="define" use="required"
    		type="zclAttributeDefine" />
    	<xs:attribute name="introducedIn" type="zclSpecVersion" />
    	<xs:attribute name="length" type="xs:integer" />
    	<xs:attribute name="manufacturerCode" type="zclCode" />
    	<xs:attribute name="max" type="xs:anySimpleType" />
    	<xs:attribute name="min" type="xs:anySimpleType" />
    	<xs:attribute name="optional" use="required" type="xs:boolean" />
    	<xs:attribute name="side" use="required" type="zclSide" />
    	<xs:attribute name="type" use="required" type="xs:string" />
    	<xs:attribute name="readable" type="xs:boolean" />
    	<xs:attribute name="writable" type="xs:boolean" />
    	<xs:attribute name="reportable" type="xs:boolean" />
    	<xs:attribute name="array" type="xs:boolean"></xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="description">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="arg" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="arg">
        <xs:annotation>
        	<xs:documentation>An optional attribute, that specifies the length argument.

This is used in cases where a length argument is preceding the actual array.

In those cases, an array becomes a known length, and you can have variable length arguments after it.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
        <xs:attribute name="arrayLength" type="xs:boolean" />
    	<xs:attribute name="array" type="xs:boolean" />
    	<xs:attribute name="default" type="xs:string" />
    	<xs:attribute name="description" type="xs:string" />
    	<xs:attribute name="introducedIn" type="zclSpecVersion" />
    	<xs:attribute name="removedIn" type="zclSpecVersion"></xs:attribute>
    	<xs:attribute name="name" use="required" />
    	<xs:attribute name="type" use="required" />
    	<xs:attribute name="length" type="xs:int"></xs:attribute>
    	<xs:attribute name="presentIf" type="xs:string" />
    	<xs:attribute name="optional" type="xs:integer" />
    	<xs:attribute name="countArg" type="xs:string" use="optional"></xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="zclAttributeDefine">
    <xs:restriction base="xs:string"></xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="zclCommandName">
    <xs:restriction base="xs:string"></xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="zclSpecVersion">
    <xs:restriction base="xs:string"></xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="zclCode">
    <xs:restriction base="xs:string"></xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="zclSide">
    <xs:restriction base="xs:string">
      <xs:enumeration value="client"></xs:enumeration>
      <xs:enumeration value="server"></xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="zclSideWithEither">
    <xs:restriction base="xs:string">
      <xs:enumeration value="client"></xs:enumeration>
      <xs:enumeration value="server"></xs:enumeration>
      <xs:enumeration value="either"></xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="mapping">
    <xs:complexType>
      <xs:attribute name="code" type="xs:string" />
      <xs:attribute name="translation" type="xs:string" />
    </xs:complexType>
  </xs:element>

  <xs:element name="map">
    <xs:complexType>
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" ref="mapping" />
        </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== project-chip/connectedhomeip/src/app/zap-templates/zcl/data-model/chip/application-launcher-cluster.xml
<?xml version="1.0"?>
<!--
Copyright (c) 2021-2026 Project CHIP Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
<!--
XML generated by Alchemy; DO NOT EDIT.
Source: src/app_clusters/media/ApplicationLauncher.adoc
Parameters: zap ignore-errored provisional-policy=loose sdkRoot=./connectedhomeip/ specRoot=./connectedhomeip-spec/ attribute=ambient-context-sensor,ambientsensing,cameras,cameras-image-rotation,groupcast,hrap-pdc,hrap-tbrd,hvac-thermostat-events,hvac-thermostat-suggestions,improved-capabilities-tcr,partitioned-crl,security-sensor-events-tcr,tcr-smokeco-unmounted-state,temperature-alarm,thread-commissioning ./connectedhomeip-spec/src/app_clusters/media/ApplicationLauncher.adoc 
Git: 1.6-185-gb051f7083
Alchemy: v1.6.18
-->
<configurator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../zcl.xsd">
  <domain name=""/>
  <enum name="StatusEnum" type="enum8">
    <cluster code="0x050C"/>
    <item name="Success" value="0x00"/>
    <item name="AppNotAvailable" value="0x01"/>
    <item name="SystemBusy" value="0x02"/>
    <item name="PendingUserApproval" value="0x03"/>
    <item name="Downloading" value="0x04"/>
    <item name="Installing" value="0x05"/>
  </enum>

  <struct name="ApplicationEPStruct">
    <cluster code="0x050C"/>
    <item fieldId="0" name="Application" type="ApplicationStruct"/>
    <item fieldId="1" name="Endpoint" type="endpoint_no" optional="true"/>
  </struct>

  <struct name="ApplicationStruct">
    <cluster code="0x050C"/>
    <item fieldId="0" name="CatalogVendorID" type="int16u"/>
    <item fieldId="1" name="ApplicationID" type="char_string"/>
  </struct>

  <cluster>
    <domain>Media</domain>
    <name>Application Launcher</name>
    <code>0x050C</code>
    <define>APPLICATION_LAUNCHER_CLUSTER</define>
    <description>This cluster provides an interface for launching applications on a Video Player device such as a TV.</description>
    <client init="false" tick="false">true</client>
    <server init="false" tick="false">true</server>
    <globalAttribute code="0xFFFD" side="either" value="2"/>
    <features>
      <feature bit="0" code="AP" name="ApplicationPlatform" summary="Support for attributes and commands required for endpoint to support launching any application within the supported application catalogs">
        <optionalConform/>
      </feature>
    </features>
    <attribute code="0x0000" side="server" name="CatalogList" define="APPLICATION_LAUNCHER_LIST" type="array" entryType="int16u" optional="true">
      <mandatoryConform>
        <feature name="AP"/>
      </mandatoryConform>
    </attribute>
    <attribute code="0x0001" side="server" name="CurrentApp" define="APPLICATION_LAUNCHER_CURRENT_APP" type="ApplicationEPStruct" isNullable="true" optional="true">
      <optionalConform/>
    </attribute>
    <command code="0x00" source="client" name="LaunchApp" response="LauncherResponse">
      <description>Upon receipt of this command, the server SHALL launch the application with optional data.</description>
      <arg fieldId="0" name="Application" type="ApplicationStruct" optional="true"/>
      <arg fieldId="1" name="Data" type="octet_string" optional="true"/>
    </command>

    <command code="0x01" source="client" name="StopApp" response="LauncherResponse">
      <description>Upon receipt of this command, the server SHALL stop the application if it is running.</description>
      <arg fieldId="0" name="Application" type="ApplicationStruct" optional="true"/>
    </command>

    <command code="0x02" source="client" name="HideApp" response="LauncherResponse">
      <description>Upon receipt of this command, the server SHALL hide the application.</description>
      <arg fieldId="0" name="Application" type="ApplicationStruct" optional="true"/>
    </command>

    <command code="0x03" source="server" name="LauncherResponse" disableDefaultResponse="true">
      <description>This command SHALL be generated in response to LaunchApp/StopApp/HideApp commands.</description>
      <arg fieldId="0" name="Status" type="StatusEnum" max="0x05"/>
      <arg fieldId="1" name="Data" type="octet_string" optional="true"/>
    </command>

  </cluster>
</configurator>

=== project-chip/connectedhomeip/src/app/zap-templates/zcl/data-model/chip/account-login-cluster.xml
<?xml version="1.0"?>
<!--
Copyright (c) 2021-2026 Project CHIP Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
<!--
XML generated by Alchemy; DO NOT EDIT.
Source: src/app_clusters/media/AccountLogin.adoc
Parameters: zap ignore-errored provisional-policy=loose sdkRoot=./connectedhomeip/ specRoot=./connectedhomeip-spec/ attribute=ambient-context-sensor,ambientsensing,cameras,cameras-image-rotation,groupcast,hrap-pdc,hrap-tbrd,hvac-thermostat-events,hvac-thermostat-suggestions,improved-capabilities-tcr,partitioned-crl,security-sensor-events-tcr,tcr-smokeco-unmounted-state,temperature-alarm,thread-commissioning ./connectedhomeip-spec/src/app_clusters/media/AccountLogin.adoc 
Git: 0.9-fall2026-221-g02e23241b
Alchemy: v1.7.4
-->
<configurator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../zcl.xsd">
  <domain name="CHIP"/>
  <cluster>
    <domain>Media</domain>
    <name>Account Login</name>
    <code>0x050E</code>
    <define>ACCOUNT_LOGIN_CLUSTER</define>
    <description>This cluster provides commands that facilitate user account login on a Content App or a node.</description>
    <client init="false" tick="false">true</client>
    <server init="false" tick="false">true</server>
    <globalAttribute code="0xFFFD" side="either" value="2"/>
    <command code="0x00" source="client" name="GetSetupPIN" isFabricScoped="true" response="GetSetupPINResponse" mustUseTimedInvoke="true">
      <description>The purpose of this command is to determine if the active user account of the given Content App matches the active user account of a given Commissionee, and when it does, return a Setup PIN which can be used for password-authenticated session establishment (PASE) with the Commissionee.</description>
      <access op="invoke" privilege="administer"/>
      <arg fieldId="0" name="TempAccountIdentifier" type="char_string" length="100" minLength="16"/>
    </command>

    <command code="0x01" source="server" name="GetSetupPINResponse" isFabricScoped="true" disableDefaultResponse="true">
      <description>This message is sent in response to the GetSetupPIN command, and contains the Setup PIN, or null when the account identified in the request does not match the active account of the running Content App.</description>
      <arg fieldId="0" name="SetupPIN" type="char_string"/>
    </command>

    <command code="0x02" source="client" name="Login" isFabricScoped="true" mustUseTimedInvoke="true">
      <description>The purpose of this command is to allow the Content App to assume the user account of a given Commissionee by leveraging the Setup PIN input by the user during the commissioning process.</description>
      <access op="invoke" privilege="administer"/>
      <arg fieldId="0" name="TempAccountIdentifier" type="char_string" length="100" minLength="16"/>
      <arg fieldId="1" name="SetupPIN" type="char_string" minLength="8"/>
      <arg fieldId="2" name="Node" type="node_id" optional="true"/>
    </command>

    <command code="0x03" source="client" name="Logout" isFabricScoped="true" mustUseTimedInvoke="true">
      <description>The purpose of this command is to instruct the Content App to clear the current user account.</description>
      <arg fieldId="0" name="Node" type="node_id" optional="true"/>
    </command>

    <event code="0x0000" name="LoggedOut" priority="critical" side="server" isFabricSensitive="true" optional="true">
      <description>This event can be used by the Content App to indicate that the current user has logged out.</description>
      <access op="read" privilege="administer"/>
      <field id="0" name="Node" type="node_id" optional="true"/>
      <optionalConform/>
    </event>

  </cluster>
</configurator>

=== project-chip/connectedhomeip/src/app/zap-templates/zcl/data-model/chip/media-input-cluster.xml
<?xml version="1.0"?>
<!--
Copyright (c) 2021-2025 Project CHIP Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
<!--
XML generated by Alchemy; DO NOT EDIT.
Source: src/app_clusters/media/MediaInput.adoc
Parameters: 
Git: 0.9-fall2025-24-g510f6eac9
-->
<configurator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../zcl.xsd">
  <domain name="CHIP"/>
  <cluster>
    <domain>Media</domain>
    <name>Media Input</name>
    <code>0x0507</code>
    <define>MEDIA_INPUT_CLUSTER</define>
    <client init="false" tick="false">true</client>
    <server init="false" tick="false">true</server>
    <description>This cluster provides an interface for controlling the Input Selector on a media device such as a TV.</description>
    <globalAttribute code="0xFFFD" side="either" value="1"/>
    <features>
      <feature bit="0" code="NU" name="NameUpdates" summary="Supports updates to the input names">
        <optionalConform/>
      </feature>
    </features>
    <attribute side="server" code="0x0000" name="InputList" define="MEDIA_INPUT_LIST" type="array" entryType="InputInfoStruct"/>
    <attribute side="server" code="0x0001" name="CurrentInput" define="MEDIA_INPUT_CURRENT_INPUT" type="int8u"/>
    <command source="client" code="0x00" name="SelectInput">
      <description>Upon receipt, this command SHALL change the media input on the device to the input at a specific index in the Input List.</description>
      <arg id="0" name="Index" type="int8u"/>
    </command>

    <command source="client" code="0x01" name="ShowInputStatus">
      <description>Upon receipt, this command SHALL display the active status of the input list on screen.</description>
    </command>

    <command source="client" code="0x02" name="HideInputStatus">
      <description>Upon receipt, this command SHALL hide the input list from the screen.</description>
    </command>

    <command source="client" code="0x03" name="RenameInput" optional="true">
      <description>Upon receipt, this command SHALL rename the input at a specific index in the Input List.</description>
      <access op="invoke" privilege="manage"/>
      <arg id="0" name="Index" type="int8u"/>
      <arg id="1" name="Name" type="char_string"/>
      <mandatoryConform>
        <feature name="NU"/>
      </mandatoryConform>
    </command>

  </cluster>

  <struct name="InputInfoStruct">
    <cluster code="0x0507"/>
    <item fieldId="0" name="Index" type="int8u"/>
    <item fieldId="1" name="InputType" type="InputTypeEnum" max="0x0B"/>
    <item fieldId="2" name="Name" type="char_string"/>
    <item fieldId="3" name="Description" type="char_string"/>
  </struct>

  <enum name="InputTypeEnum" type="enum8">
    <cluster code="0x0507"/>
    <item name="Internal" value="0x00"/>
    <item name="Aux" value="0x01"/>
    <item name="Coax" value="0x02"/>
    <item name="Composite" value="0x03"/>
    <item name="HDMI" value="0x04"/>
    <item name="Input" value="0x05"/>
    <item name="Line" value="0x06"/>
    <item name="Optical" value="0x07"/>
    <item name="Video" value="0x08"/>
    <item name="SCART" value="0x09"/>
    <item name="USB" value="0x0A"/>
    <item name="Other" value="0x0B"/>
  </enum>
</configurator>
